version: "3.8"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2.5
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wiki
      DB_USER: wikijs
      DB_PASS: wikijsrocks
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wiki
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN:?}

volumes:
  db-data:
